language: emacs-lisp
os:
  - linux
cache: apt
env:
  global:
   # GH_TOKEN=[secure]             (to push to osx/windows repo under soonhokong)
   - secure: "LAgBomK36BzF2mN/lOwua+gDzLgF6RyuMYBjMlP5KY3knUZT8m/9wff2GlWGm87anb6aIJH69ERjVyFU4sWi9qcD+26vs1m9agMFxuqTfpibeDoz/rd9D/9LA3mNeO6v5kR2FTQ/OTTC6nMC4olRxdzz22Jg9ly7cNzfFPuSGFA="
   # REPO=BLESSED                  (to perform extra stuff only for pushes to the blessed repo)
   - secure: "Du/ZXFXdhRZL6AU6t6G8A3BNr3oPpHK4h2UCK00b+bgonHy7kDgTE0YxRVOf8VpXqfJwekzT4hWJhnKXasTp5avNEVEbdWC4nyM4tZbl6a8g8iI3Oo+JB6seSO6fIhrv6sZ7BCa6iuKDwzWJ0sQnXL+kx/zUqcle5eVUu5ic/24="
  matrix:
   - EVM_EMACS=emacs-24.3-bin
   - EVM_EMACS=emacs-24.4-bin

before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install $EVM_EMACS --use
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
  - evm list
  - sudo add-apt-repository --yes ppa:leanprover/lean
  - sudo apt-get update
  - sudo apt-get -q -y upgrade
  - sudo apt-get install mercurial python2.7 texlive-latex-recommended texlive-humanities texlive-xetex texlive-science texlive-latex-extra texlive-fonts-recommended || true
  - tar xvfz header/l3kernel.tar.gz -C ~/

install:
  - sudo apt-get -qq install lean

script:
  - EMACS_BIN=$(evm bin $EVM_EMACS) make

after_script:
  - if [[ $REPO == BLESSED ]]; then
      git config --global user.email "notifications@travis-ci.org";
      git config --global user.name "Travis CI";
      git checkout --orphan gh-pages;
      rm .git/index;
      git add -f *.html tutorial.pdf tutorial.html;
      git add css;
      git add fonts;
      git add js;
      git clean -fxd;
      git commit -m "Update `date -R`";
      git push -q https://soonhokong:${GH_TOKEN}@github.com/leanprover/tutorial.git +HEAD:gh-pages;
    fi
  - make test

notifications:
  email:
    recipients:
     - lean-build@googlegroups.com
